In [1]:
import nfl_data_py as nfl

In [24]:
import pandas as pd

In [25]:
pd.set_option("display.max_columns", None)

In [3]:
pbp_data = nfl.import_pbp_data([2024], downcast=True, cache=False, alt_path=None)

2024 done.
Downcasting floats.

In [4]:
pbp_data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
0,1.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,,,None,NA;NA,Kaiir Elam;Ja'Marcus Ingram;Max Melton;Kameron...,NA;NA,CB;CB;CB;DE;FB;FS;FS;FS;FS;ILB;ILB;ILB;ILB;K;O...,NA;NA,5;46;16;96;41;21;39;32;42;52;54;51;44;2;52;26;...
2,61.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,,,None,NA;NA,Evan Brown;Hjalte Froholdt;Rasul Douglas;Taron...,NA;NA,C;C;CB;CB;CB;DE;DE;DT;DT;G;MLB;OLB;QB;RB;SS;SS...,NA;NA,62;72;31;7;47;57;50;92;91;76;43;42;1;6;9;3;73;...
3,83.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,SCREEN,ZONE_COVERAGE,COVER_3,NA;NA,Evan Brown;Hjalte Froholdt;Rasul Douglas;Taron...,NA;NA,C;C;CB;CB;CB;DE;DE;DT;DT;G;MLB;OLB;QB;RB;SS;SS...,NA;NA,62;72;31;7;47;57;50;92;91;76;43;42;1;6;9;3;73;...
4,108.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,HITCH/CURL,ZONE_COVERAGE,COVER_3,NA;NA,Evan Brown;Hjalte Froholdt;Rasul Douglas;Taron...,NA;NA,C;C;CB;CB;CB;DE;DE;DT;DT;G;MLB;OLB;QB;RB;SS;SS...,NA;NA,62;72;31;7;47;40;57;92;91;76;43;42;1;6;9;3;73;...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49487,4158.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,...,0.0,,,None,Avonte Maddox;Tristin McCollum;Oren Burks;Zack...,Joshua Williams;Nazeeh Johnson;Drue Tranquill;...,CB;FS;OLB;OLB;RB;RB;SS;TE;TE;TE;WR;NA;NA,CB;CB;ILB;ILB;K;OLB;RB;SS;TE;WR;WR;NA;NA,29;36;42;53;14;28;32;88;81;84;6;NA;NA,2;13;23;50;7;54;42;21;83;84;81;NA;NA
49488,4181.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,...,0.0,,,None,Landon Dickerson;Tyler Steen;Kenny Pickett;Ken...,Trent McDuffie;Jaylen Watson;Michael Danna;Fel...,G;G;QB;RB;RB;T;T;T;TE;TE;WR;NA;NA,CB;CB;DE;DE;DT;DT;ILB;ILB;OLB;SS;SS;NA;NA,69;56;7;14;28;68;64;74;81;84;80;NA;NA,22;35;51;97;91;98;23;32;54;20;21;NA;NA
49489,4203.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,...,0.0,,,None,Landon Dickerson;Tyler Steen;Kenny Pickett;Ken...,Trent McDuffie;Jaylen Watson;Michael Danna;Fel...,G;G;QB;RB;RB;T;T;T;TE;TE;WR;NA;NA,CB;CB;DE;DE;DT;DT;ILB;ILB;OLB;SS;SS;NA;NA,69;56;7;14;28;68;64;74;81;84;80;NA;NA,22;35;51;97;91;98;23;32;54;20;21;NA;NA
49490,4225.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,...,0.0,,,None,Landon Dickerson;Tyler Steen;Kenny Pickett;Ken...,Trent McDuffie;Jaylen Watson;Michael Danna;Fel...,G;G;QB;RB;RB;T;T;T;TE;TE;WR;NA;NA,CB;CB;DE;DE;DT;DT;ILB;ILB;OLB;SS;SS;NA;NA,69;56;7;14;28;68;64;74;81;84;80;NA;NA,22;35;51;97;91;98;23;32;54;20;21;NA;NA
49491,4247.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
pbp_data.columns

Index(['play_id', 'game_id', 'old_game_id_x', 'home_team', 'away_team',
       'season_type', 'week', 'posteam', 'posteam_type', 'defteam',
       ...
       'was_pressure', 'route', 'defense_man_zone_type',
       'defense_coverage_type', 'offense_names', 'defense_names',
       'offense_positions', 'defense_positions', 'offense_numbers',
       'defense_numbers'],
      dtype='object', length=397)

In [21]:
fourth_down_data = pbp_data[pbp_data['down'] == 4]

In [32]:
fourth_down_conversion_data = fourth_down_data[~fourth_down_data['play_type'].isin(['punt', 'field_goal'])]

In [12]:
nfl.see_pbp_cols().tolist()

['play_id',
 'game_id',
 'old_game_id',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe']

In [33]:
fourth_down_conversion_data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,nflverse_game_id,old_game_id_y,possession_team,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
103,2632.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,12.0,2024-09-08,204.0,1104.0,1104.0,Half2,0.0,12.0,0.0,3.0,4.0,0,03:24,ARI 12,1.0,21.0,(3:24) 17-J.Allen up the middle to ARI 11 for ...,run,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,middle,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,17.0,17.0,17.0,17.0,0.0,17.0,17.0,0.0,0.006518,0.029227,0.000649,0.055303,0.495588,0.000986,0.411729,0.0,0.0,3.894738,1.343717,3.034041,-3.034041,-0.281947,0.281947,1.877157,-1.877157,NaN,NaN,0.000000,0.000000,5.277059,-5.277059,-4.309857,4.309857,4.396249,-4.396249,-4.030437,4.030437,0.636436,0.363564,0.636436,0.363564,0.063095,0.047678,0.047678,0.699531,0.300469,0.718930,0.718930,-0.125627,0.125627,0.156182,-0.156182,NaN,NaN,0.000000,0.000000,0.086387,-0.086387,0.032495,-0.032495,0.086835,-0.086835,0.015222,-0.015222,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0034857,J.Allen,1.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,00-0036933,Z.Collins,ARI,00-0034375,K.White,ARI,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2024,NaN,NaN,37.0,1.0,First down,2632.0,"9/8/24, 13:03:02",2024-09-08T19:00:32.253Z,Highmark Stadium,"Clouds and sun with wind Temp: 61° F, Humidity...",7d40236a-1312-11ef-afd1-646009f18b2e,0,0.0,RUSH,0.0,None,2024-09-08T19:00:34.153Z,None,12.0,Touchdown,2024-09-08T18:58:31.313Z,5.0,2:48,2.0,1.0,1.0,3.0,3.0,0.0,FUMBLE,TOUCHDOWN,05:25,02:37,ARI 21,ARI 11,2561.0,2684.0,28,34,Home,6,62,6.5,46.0,0,outdoors,a_turf,61.0,20.0,Sean McDermott,Jonathan Gannon,BUF00,New Era Field,0.0,1.0,None,NaN,J.Allen,17.0,None,NaN,0.0,1.0,1.0,0.0,1.0,None,00-0034857,None,J.Allen,17.0,00-0034857,J.Allen,00-0034857,J.Allen,00-0034857,0.0,0.0,1.343717,NaN,NaN,NaN,NaN,NaN,0.161714,-16.171412,2024_01_ARI_BUF,2024090801,BUF,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",8.0,"2 CB, 2 DT, 1 FS, 2 ILB, 1 NT, 2 OLB, 1 SS",0.0,00-0035679;00-0035239;00-0038663;00-0034677;00...,00-0035679;00-0035668;00-0038548;00-0034857;00...,00-0035239;00-0038663;00-0034677;00-0038623;00...,11.0,11.0,NaN,NaN,0.0,,,None,Connor McGovern;David Edwards;O'Cyrus Torrence...,Sean Murphy-Bunting;Starling Thomas V;Justin J...,C;G;G;QB;RB;T;T;TE;TE;WR;WR;NA;NA,CB;CB;DT;DT;FS;ILB;ILB;NT;OLB;OLB;SS;NA;NA,66;76;64;17;4;73;79;88;86;13;0;NA;NA,23;24;93;55;34;7;2;95;45;25;3;NA;NA
123,3124.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,37.0,2024-09-08,643.0,643.0,643.0,Half2,0.0,14.0,0.0,4.0,4.0,0,10:43,ARI 37,2.0,70.0,(10:43) (Shotgun) 17-J.Allen scrambles right e...,run,5.0,1.0,0.0,1.0,0.0,0.0,1.0,None,None,NaN,NaN,right,end,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,24.0,20.0,24.0,20.0,4.0,24.0,20.0,4.0,0.064229,0.135570,0.001456,0.208476,0.256944,0.006440,0.326886,0.0,0.0,1.202964,2.453890,5.164072,-5.164072,-0.465450,0.465450,4.980997,-4.980997,NaN,NaN,0.000000,0.000000,4.397336,-4.397336,-0.257871,0.257871,3.036338,-3.036338,0.433315,-0.433315,0.768989,0.231011,0.768989,0.231011,0.056800,0.049371,0.049371,0.825789,0.174211,0.825451,0.825451,-0.092206,0.092206,0.284478,-0.284478,NaN,NaN,0.000000,0.000000,0.083403,-0.083403,0.165198,-0.165198,0.096762,-0.096762,0.133592,-0.133592,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0034857,J.Allen,5.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ARI,None,00-0034375,None,K.White,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2024,NaN,NaN,43.0,1.0,First down,3124.0,"9/8/24, 13:03:02",2024-09-08T19:22:21.770Z,Highmark Stadium,"Clouds and sun with wind Temp: 61° F, Humidity...",7d40236a-1312-11ef-afd1-646009f18b2e,0,0.0,RUSH,0.0,None,2024-09-08T19:22:27.913Z,None,14.0,Touchdown,2024-09-08T19:17:34.370Z,10.0,4:48,4.0,1.0,1.0,4.0,4.0,-5.0,KICKOFF,TOUCHDOWN,13:32,08:44,BUF 30,ARI 6,2941.0,3253.0,28,34,Home,6,62,6.5,46.0,0,outdoors,a_turf,61.0,20.0,Sean McDermott,Jonathan Gannon,BUF00,New Era Field,0.0,1.0,J.Allen,17.0,None,17.0,None,NaN,1.0,0.0,1.0,0.0,1.0,00-0034857,None,None,J.Allen,17.0,00-0034857,J.Allen,00-0034857,J.Allen,00-0034857,1.0,0.0,2.453890,NaN,NaN,NaN,NaN,NaN,0.791056,20.894444,2024_01_ARI_BUF,2024090801,BUF,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",6.0,"3 CB, 2 DT, 1 FS, 1 ILB, 1 NT, 2 OLB, 1 SS",5.0,00-0035679;00-0035239;00-0039007;00-0038663;00...,00-0035679;00-0035668;00-0038548;00-0034857;00...,00-0035239;00-0039007;00-0038663;00-0034677;00...,11.0,11.0,NaN,NaN,1.0,,MAN_COVERAGE,COVER_1,Connor McGovern;David Edwards;O'Cyrus Torrence...,Sean Murphy-Bunting;Garrett Williams;Starling ...,C;G;G;QB;RB;T;T;TE;WR;WR;WR;NA;NA,CB;CB;CB;DT;DT;FS;ILB;NT;OLB;OLB;SS;NA;NA,66;76;64;17;26;73;79;86;13;10;0;NA;NA,23;21;24;93;55;34;7;98;45;25;3;NA;NA
160,4062.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,BUF,29.0,2024-09-08,32.0,32.0,32.0,Half2,0.0,19.0,0.0,4.0,4.0,0,00:32,BUF 29,7.0,31.0,(:32) (Shotgun) 1-K.Murray pass incomplete dee...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,deep,left,27.0,NaN,None,None,None,NaN,None,None,2.0,2.0,0.0,None,None,None,None,2.0,2.0,34.0,28.0,28.0,34.0,-6.0,28.0,34.0,-6.0,0.334681,0.028458,0.000349,0.008416,0.549675,0.000414,0.078007,0.0,0.0,2.050921,-2.050921,4.580219,-4.580219,-1.487240,1.487240,10.345948,-10.345948,3.433172,-5.484093,0.000000,0.000000,5.959050,-5.959050,0.037478,-0.037478,1.807837,-1.807837,5.745664,-5.745664,0.136109,0.863891,0.863891,0.136109,-0.121808,-0.147246,0.147246,0.985699,0.014301,0.155054,0.844946,0.014507,-0.014507,0.580591,-0.580591,-0.015866,-0.105941,0.000000,0.000000,0.146840,-0.146840,0.131823,-0.131823,0.176065,-0.176065,0.285475,-0.285475,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0035228,K.Murray,NaN,00-0035500,G.Dortch,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,00-0037661,J.Ingram,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2024,0.267047,-26.704735,54.0,0.0,Turnover on downs,4062.0,"9/8/24, 13:03:02",2024-09-08T20:00:43Z,Highmark Stadium,"Clouds and sun with wind Temp: 61° F, Humidity...",7d40236a-1312-11ef-afd1-646009f18b2e,0,0.0,PASS,0.0,None,None,None,19.0,Turnover on downs,2024-09-08T19:55:00Z,9.0,1:30,2.0,0.0,0.0,4.0,4.0,0.0,KICKOFF,DOWNS,01:56,00:26,ARI 40,BUF 29,3790.0,4062.0,28,34,Home,6,62,6.5,46.0,0,outdoors,a_turf,61.0,20.0,Sean McDermott,Jonathan Gannon,BUF00,New Era Field,0.0,0.0,K.Murray,1.0,None,NaN,G.Dortch,4.0,1.0,0.0,0.0,0.0,1.0,00-0035228,None,00-0035500,K.Murray,1.0,00-0035228,G.Dortch,00-0035500,G.Dortch,00-0035500,0.0,0.0,-2.050921,1.230876,1.526292,2.0,1.000000,1.000000,0.990227,0.977290,2024_01_ARI_BUF,2024090801,ARI,SHOTGUN,,6.0,"2 C, 3 CB, 3 DE, 1 DT, 1 FS, 1 G, 1 MLB, 1 QB,...",6.0,00-0034495;00-0035258;00-0033551;00-0037288;00...,NA;NA,00-0034495;00-0035258;00-0033551;00-0037288;00...,0.0,22.0,NaN,2.4,0.0,CORNER,MAN_COVERAGE,COVER_1,NA;NA,Evan Brown;Hjalte Froholdt;Rasul Douglas;Chris...,NA;NA,C;C;CB;CB;CB;DE;DE;DE;DT;FS;G;MLB;QB;RB;SS;SS;...,NA;NA,62;72;31;47;46;40;57;50;91;39;76;43;1;6;9;3;68...
213,1265.0,2024_01_BAL_KC,2024090500,KC,BAL,REG,1,BAL,away,KC,50,50.0,2024-09-05,585.0,585.0,2385.0,Half1,0.0,7.0,0.0,2.0,4.0,0,09:45,MID 50,3.0,21.0,(9:45) (Shotgun) 8-L.Jackson pass short right ...,pass,1.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,-1.0,2.0,None,None,None,NaN,None,None,2.0,3.0,0.0,None,None,None,None,3.0,2.0,10.0,7.0,7.0,10.0,-3.0,7.0,10.0,-3.0,0.143701,0.168730,0.001926,0.241725,0.154371,0.003906,0.285640,0.0,0.0,0.268286,-2.652661,6.768323,-6.768323,-0.478727,0.478727,6.399100,-6.399100,-2.570078,-0.082584,-2.570078,-0.082584,2.200689,-2.200689,1.939834,-1.939834,7.820277,-7.820277,-4.263004,4.263004,0.319890,0.680110,0.680110,0.319890,-0.077797,-0.019793,0.019793,0.757907,0.242093,0.284015,0.715985,-0.021402,0.021402,0.091622,-0.091622,0.325411,-0.403208,0.325411,-0.403208,-0.330572,0.330572,0.354643,-0.354643,-0.330572,0.330572,0.341297,-0.341297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0034796,L.Jackson,1.0,00-0039064,Z.Flowers,1.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,KC,None,00-0037191,None,T.McDuffie,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2024,0.820005,17.999512,16.0,0.0,Turnover on downs,1265.0,"9/5/24, 20:44:42",2024-09-06T01:33:58.503Z,GEHA Field at Arrowhead Stadium,"Temp: 67° F, Humidity: 53%, Wind: NE 8 mph",7d3e8f84-1312-11ef-afd1-646009f18b2e,0,0.0,PASS,0.0,None,2024-09-06T01:34:03.327Z,None,7.0,Turnover on downs,2024-09-06T01:28:33.187Z,6.0,3:58,1.0,0.0,0.0,2.0,2.0,-10.0,KICKOFF,DOWNS,13:37,09:39,BAL 30,50,1084.0,1265.0,20,27,Home,7,47,3.0,46.0,0,outdoors,grass,67.0,8.0,Andy Reid,John Harbaugh,KAN00,GEHA Field at Arrowhead Stadium,0.0,0.0,L.Jackson,8.0,None,NaN,Z.Flowers,4.0,1.0,0.0,0.0,0.0,1.0,00-0034796,None,00-0039064,L.Jackson,8.0,00-0034796,Z.Flowers,00-0039064,Z.Flowers,00-0039064,0.0,0.0,-2.652661,3.780485,7.581516,6.0,0.674891,0.674891,0.847347,15.265327,2024_01_BAL_KC,2024090500,BAL,SHOTGUN,,7.0,"1 C, 2 CB, 2 DE, 1 DT, 1 FB, 1 FS, 1 G, 2 ILB,...",4.0,00-0037825;00-0037191;00-0037195;00-0036378;00...,NA;NA,00-0037825;00-0037191;00-0037195;00-0036378;00...,0.0,22.0,NaN,1.3,0.0,QUICK OUT,ZONE_COVERAGE,COVER_3,NA;NA,Tyler Linderbaum;Trent McDuffie;Jaylen Watson;...,NA;NA,C;CB;CB;DE;DE;DT;FB;FS;G;ILB;ILB;NT;OLB;QB;RB;...,NA;NA,64;22;35;51;56;95;42;6;72;23;32;69;54;8;22;20;...

In [66]:
relevant_fourth_down_data = fourth_down_data.iloc[:, list(range(42)) + list(range(54,64)) + list(range(69, 70)) + list(range(125, 130))]

In [67]:
relevant_fourth_down_data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,td_prob,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception
31,823.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,BUF,11.0,2024-09-08,900.0,900.0,2700.0,Half1,0.0,3.0,1.0,2.0,4.0,0,15:00,BUF 11,4.0,60.0,"(15:00) 5-M.Prater 29 yard field goal is GOOD,...",field_goal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,3.0,0.0,10.0,7.0,0.0,7.0,10.0,0.0,10.0,0.002077,0.010744,0.0,0.0,0.0,0.0,0.0
43,1120.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,19.0,2024-09-08,591.0,591.0,2391.0,Half1,0.0,4.0,1.0,2.0,4.0,1,09:51,ARI 19,19.0,51.0,"(9:51) 2-T.Bass 37 yard field goal is GOOD, Ce...",field_goal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,3.0,3.0,10.0,0.0,10.0,-10.0,3.0,10.0,-7.0,0.014307,0.020978,0.0,0.0,0.0,0.0,0.0
93,2360.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,ARI,74.0,2024-09-08,483.0,1383.0,1383.0,Half2,0.0,9.0,0.0,3.0,4.0,0,08:03,ARI 26,14.0,-4.0,"(8:03) 12-B.Gillikin punts 50 yards to BUF 24,...",punt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,3.0,17.0,17.0,17.0,17.0,0.0,17.0,17.0,0.0,0.015738,0.200151,0.0,0.0,0.0,0.0,0.0
97,2468.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,BUF,66.0,2024-09-08,388.0,1288.0,1288.0,Half2,0.0,10.0,0.0,3.0,4.0,0,06:28,BUF 34,7.0,3.0,"(6:28) 8-S.Martin punts 51 yards to ARI 15, Ce...",punt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,3.0,17.0,17.0,17.0,17.0,0.0,17.0,17.0,0.0,0.020030,0.273981,0.0,0.0,0.0,0.0,0.0
103,2632.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,12.0,2024-09-08,204.0,1104.0,1104.0,Half2,0.0,12.0,0.0,3.0,4.0,0,03:24,ARI 12,1.0,21.0,(3:24) 17-J.Allen up the middle to ARI 11 for ...,run,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,middle,None,3.0,17.0,17.0,17.0,17.0,0.0,17.0,17.0,0.0,0.006518,0.411729,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49431,2834.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,KC,away,PHI,KC,53.0,2025-02-09,170.0,1070.0,1070.0,Half2,0.0,17.0,0.0,3.0,4.0,0,02:50,KC 47,4.0,17.0,(2:50) (Shotgun) 15-P.Mahomes pass incomplete ...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,4.0,NaN,None,None,2.0,27.0,0.0,0.0,27.0,-27.0,0.0,27.0,-27.0,0.020714,0.304604,0.0,1.0,1.0,0.0,0.0
49453,3344.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,30.0,2025-02-09,596.0,596.0,596.0,Half2,0.0,20.0,1.0,4.0,4.0,0,09:56,KC 30,13.0,40.0,"(9:56) 4-J.Elliott 48 yard field goal is GOOD,...",field_goal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,2.0,37.0,6.0,34.0,6.0,28.0,37.0,6.0,31.0,0.023107,0.041325,0.0,0.0,0.0,0.0,0.0
49461,3510.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,27.0,2025-02-09,485.0,485.0,485.0,Half2,0.0,22.0,0.0,4.0,4.0,0,08:05,KC 27,4.0,1.0,(8:05) (Field Goal formation) PENALTY on PHI-6...,no_play,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,1.0,37.0,6.0,37.0,6.0,31.0,37.0,6.0,31.0,0.057449,0.110841,0.0,0.0,0.0,0.0,0.0
49462,3547.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,32.0,2025-02-09,485.0,485.0,485.0,Half2,0.0,22.0,1.0,4.0,4.0,0,08:05,KC 32,9.0,1.0,"(8:05) 4-J.Elliott 50 yard field goal is GOOD,...",field_goal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,1.0,40.0,6.0,37.0,6.0,31.0,40.0,6.0,34.0,0.041057,0.036143,0.0,0.0,0.0,0.0,0.0
49484,4093.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,50,50.0,2025-02-09,119.0,119.0,119.0,Half2,0.0,24.0,0.0,4.0,4.0,0,01:59,MID 50,6.0,4.0,(1:59) (Shotgun) 7-K.Pickett pass incomplete s...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,left,6.0,NaN,None,None,0.0,40.0,14.0,40.0,14.0,26.0,40.0,14.0,26.0,0.721674,0.082879,0.0,1.0,1.0,0.0,0.0

In [68]:
relevant_fourth_down_conversion_data = fourth_down_conversion_data.iloc[:, list(range(42)) + list(range(54,64)) + list(range(69, 70)) + list(range(125, 130))]

In [69]:
relevant_fourth_down_conversion_data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,td_prob,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception
103,2632.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,12.0,2024-09-08,204.0,1104.0,1104.0,Half2,0.0,12.0,0.0,3.0,4.0,0,03:24,ARI 12,1.0,21.0,(3:24) 17-J.Allen up the middle to ARI 11 for ...,run,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,middle,None,3.0,17.0,17.0,17.0,17.0,0.0,17.0,17.0,0.0,0.006518,0.411729,1.0,0.0,0.0,0.0,0.0
123,3124.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,ARI,37.0,2024-09-08,643.0,643.0,643.0,Half2,0.0,14.0,0.0,4.0,4.0,0,10:43,ARI 37,2.0,70.0,(10:43) (Shotgun) 17-J.Allen scrambles right e...,run,5.0,1.0,0.0,1.0,0.0,0.0,1.0,None,None,NaN,NaN,right,end,3.0,24.0,20.0,24.0,20.0,4.0,24.0,20.0,4.0,0.064229,0.326886,1.0,0.0,0.0,0.0,0.0
160,4062.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,BUF,29.0,2024-09-08,32.0,32.0,32.0,Half2,0.0,19.0,0.0,4.0,4.0,0,00:32,BUF 29,7.0,31.0,(:32) (Shotgun) 1-K.Murray pass incomplete dee...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,deep,left,27.0,NaN,None,None,2.0,34.0,28.0,28.0,34.0,-6.0,28.0,34.0,-6.0,0.334681,0.078007,0.0,1.0,1.0,0.0,0.0
213,1265.0,2024_01_BAL_KC,2024090500,KC,BAL,REG,1,BAL,away,KC,50,50.0,2024-09-05,585.0,585.0,2385.0,Half1,0.0,7.0,0.0,2.0,4.0,0,09:45,MID 50,3.0,21.0,(9:45) (Shotgun) 8-L.Jackson pass short right ...,pass,1.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,-1.0,2.0,None,None,2.0,10.0,7.0,7.0,10.0,-3.0,7.0,10.0,-3.0,0.143701,0.285640,0.0,1.0,0.0,0.0,0.0
312,3584.0,2024_01_BAL_KC,2024090500,KC,BAL,REG,1,BAL,away,KC,KC,22.0,2024-09-05,394.0,394.0,394.0,Half2,0.0,18.0,0.0,4.0,4.0,0,06:34,KC 22,1.0,56.0,(6:34) 22-D.Henry left guard to KC 20 for 2 ya...,run,2.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,left,guard,3.0,27.0,17.0,17.0,27.0,-10.0,17.0,27.0,-10.0,0.114277,0.291001,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49389,1839.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,49.0,2025-02-09,116.0,116.0,1916.0,Half1,0.0,10.0,0.0,2.0,4.0,0,01:56,KC 49,3.0,17.0,"(1:56) (Punt formation) Penalty on PHI, Delay ...",None,NaN,0.0,0.0,NaN,0.0,0.0,0.0,None,None,NaN,NaN,None,None,2.0,17.0,0.0,17.0,0.0,17.0,17.0,0.0,17.0,0.000000,0.000000,NaN,NaN,NaN,0.0,NaN
49423,2616.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,6.0,2025-02-09,322.0,1222.0,1222.0,Half2,0.0,16.0,0.0,3.0,4.0,1,05:22,KC 6,6.0,69.0,(5:22) (Field Goal formation) PENALTY on PHI-4...,no_play,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,3.0,24.0,0.0,24.0,0.0,24.0,24.0,0.0,24.0,0.002282,0.045380,0.0,0.0,0.0,0.0,0.0
49431,2834.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,KC,away,PHI,KC,53.0,2025-02-09,170.0,1070.0,1070.0,Half2,0.0,17.0,0.0,3.0,4.0,0,02:50,KC 47,4.0,17.0,(2:50) (Shotgun) 15-P.Mahomes pass incomplete ...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,4.0,NaN,None,None,2.0,27.0,0.0,0.0,27.0,-27.0,0.0,27.0,-27.0,0.020714,0.304604,0.0,1.0,1.0,0.0,0.0
49461,3510.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,KC,27.0,2025-02-09,485.0,485.0,485.0,Half2,0.0,22.0,0.0,4.0,4.0,0,08:05,KC 27,4.0,1.0,(8:05) (Field Goal formation) PENALTY on PHI-6...,no_play,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,1.0,37.0,6.0,37.0,6.0,31.0,37.0,6.0,31.0,0.057449,0.110841,0.0,0.0,0.0,0.0,0.0
49484,4093.0,2024_22_KC_PHI,2025020900,PHI,KC,POST,22,PHI,home,KC,50,50.0,2025-02-09,119.0,119.0,119.0,Half2,0.0,24.0,0.0,4.0,4.0,0,01:59,MID 50,6.0,4.0,(1:59) (Shotgun) 7-K.Pickett pass incomplete s...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,left,6.0,NaN,None,None,0.0,40.0,14.0,40.0,14.0,26.0,40.0,14.0,26.0,0.721674,0.082879,0.0,1.0,1.0,0.0,0.0